### ISSUE TITLE
Support for GT3X v1

### ISSUE THREAD

**Issue by angerhang** [actigraph/pygt3x#15]
I received the following error when processing GT3X v1 https://github.com/actigraph/NHANES-GT3X-File-Format: `couldn't find log.bin`. Is GT3X V1 currently supported?

**Comment by rouzbeh** [comment]
Hi @angerhang, the quick answer is no, we don't support it yet. But I will be working on adding support.

**Comment by rouzbeh** [comment]
@angerhang Can you share the file you are trying to process?

**Comment by rouzbeh** [comment]
Hey @angerhang , the latest release of this package should support these. Have you tried it?
