### ISSUE TITLE
WARNING:pygt3x.reader:Idle sleep mode was not active at 1664449601

### ISSUE THREAD

**Issue by pradeep10kumar** [actigraph/pygt3x#34]
Why I am getting the warning of 'idle mode was active' and sometimes 'idle mode was not active'?
For example : WARNING:pygt3x.reader:Idle sleep mode was not active at 1664449601
can it read the meta data or setting as well?

**Comment by rouzbeh** [comment]
Sorry for the delay. Just in case this is still useful, yes we can read the metadata of the file. In addition, when Idle sleep mode is triggered, a spcecial record is written to the file. We read this record and then expect to read another record indicating the end of idle sleep mode.

This error message indicates that we have found a record indicating idle sleep mode was ended, but we hadn't found one saying it has been triggered.
