### ISSUE TITLE
Problem with FileReader(filename) as reader:

### ISSUE THREAD

**Issue by miahoffmannd** [actigraph/pygt3x#35]
We are getting this error: "WARNING:root:Corrupted event at 0." when trying to run the FileReader on some .gt3x files from an ActiGraph GT3X+. The reader works with most files, but has had trouble loading some of the data.

**Comment by miahoffmannd** [comment]
Looking deeper into the code, the error is raised in reader.py in the def __enter__(self) function at the line: self._get_data(self.num_rows)

**Comment by rouzbeh** [comment]
@miahoffmannd this error gets raised if the checksum verification fails when trying to read raw accelerometer data. It indicates a corrupted file. Could you possibly share an example of a file where this gets raised?
