### ISSUE TITLE
Identifying Idle Sleep Mode Records

### ISSUE THREAD

**Issue by wtroddy** [actigraph/pygt3x#45]
I'm currently helping process GT3X files, when processing these I see that idle sleep mode was activated and we can see patterns in the data that look to be correlated with the fill ISM process. The data analyst who's working on the data is asking if there's a way to identifying which records/timestamps have the data values filled as part of ISM. 

I looked through the code and it wasn't clear to me that there was any way to get that granular detail. Is there any way for the Reader to output which records get filled from ISM? 

Thanks!

**Comment by rouzbeh** [comment]
Hi,

There is currently no way to do this. But I am going to add this to version 0.7.0.
